export const BASE_WIDTH = 1487;
export const BASE_HEIGHT = 1058;

export const initialNodes = [
  { id: "root", x: 411, y: 504, r: 137, depth: 0, lines: ["An AI-assisted", "space that makes", "thinking visible"], meta: "00:18" },
  { id: "structure", x: 449, y: 238, r: 58, depth: 1, lines: ["Thought", "becomes", "structure"] },
  { id: "surface", x: 593, y: 145, r: 44, depth: 2, lines: ["Surface", "what matters"] },
  { id: "patterns", x: 683, y: 225, r: 42, depth: 2, lines: ["Reveal", "hidden", "patterns"] },
  { id: "connections", x: 600, y: 309, r: 45, depth: 2, lines: ["Make", "connections", "effortless"] },
  { id: "voice", x: 768, y: 381, r: 66, depth: 1, lines: ["Natural", "voice-first", "ideation"] },
  { id: "speak", x: 890, y: 267, r: 38, depth: 2, lines: ["Speak", "freely"] },
  { id: "capture", x: 948, y: 347, r: 46, depth: 2, lines: ["Capture", "every nuance"] },
  { id: "flow", x: 1090, y: 239, r: 47, depth: 3, lines: ["Flow", "like", "thinking"] },
  { id: "friction", x: 1200, y: 165, r: 35, depth: 4, lines: ["No friction"] },
  { id: "zone", x: 1200, y: 260, r: 38, depth: 4, lines: ["Stay in", "the zone"] },
  { id: "ai", x: 946, y: 511, r: 68, depth: 1, lines: ["AI as creative", "partner"] },
  { id: "ask", x: 1124, y: 405, r: 37, depth: 2, lines: ["Ask", "anything"] },
  { id: "suggest", x: 1177, y: 480, r: 45, depth: 2, lines: ["Get", "smart", "suggestions"] },
  { id: "challenge", x: 1212, y: 613, r: 47, depth: 3, lines: ["Challenge", "assumptions"] },
  { id: "broaden", x: 1353, y: 594, r: 41, depth: 4, lines: ["Broaden", "perspectives"] },
  { id: "stress", x: 1263, y: 745, r: 41, depth: 4, lines: ["Stress-test", "ideas"] },
  { id: "organize", x: 730, y: 611, r: 60, depth: 1, lines: ["Organize", "without", "overthinking"] },
  { id: "zoom", x: 692, y: 741, r: 35, depth: 2, lines: ["Zoom in", "with ease"] },
  { id: "context", x: 834, y: 759, r: 39, depth: 2, lines: ["Keep context", "as you grow"] },
  { id: "emerge", x: 900, y: 682, r: 37, depth: 2, lines: ["Let structure", "emerge"] },
  { id: "flexible", x: 979, y: 765, r: 38, depth: 3, lines: ["Flexible,", "not rigid"] },
  { id: "evolve", x: 959, y: 873, r: 42, depth: 4, lines: ["Adapt as", "ideas evolve"] },
  { id: "private", x: 410, y: 779, r: 53, depth: 1, lines: ["Private &", "focused", "by default"], island: true },
  { id: "yours", x: 548, y: 708, r: 38, depth: 2, lines: ["Your ideas", "stay yours"], island: true },
  { id: "calm", x: 528, y: 828, r: 39, depth: 2, lines: ["A calm space", "to think"], island: true },
  { id: "ghost-left", x: 214, y: 685, r: 55, depth: 1, lines: ["AI helps you", "find the next", "step"], ghost: true },
  { id: "ghost-top", x: 978, y: 130, r: 58, depth: 4, lines: ["AI suggests", "what you", "might miss"], ghost: true },
  { id: "ghost-right", x: 1111, y: 713, r: 56, depth: 4, lines: ["What if we", "looked at it", "this way?"], ghost: true },
];

export const initialEdges = [
  { from: "root", to: "structure", bend: -18 },
  { from: "structure", to: "surface", bend: -12 },
  { from: "structure", to: "connections", bend: 20 },
  { from: "structure", to: "patterns", bend: 2 },
  { from: "root", to: "voice", bend: -45 },
  { from: "voice", to: "speak", bend: -14 },
  { from: "voice", to: "capture", bend: 18 },
  { from: "capture", to: "flow", bend: -12 },
  { from: "flow", to: "friction", bend: -8 },
  { from: "flow", to: "zone", bend: 14 },
  { from: "root", to: "ai", bend: 30 },
  { from: "ai", to: "ask", bend: -14 },
  { from: "ai", to: "suggest", bend: 8 },
  { from: "suggest", to: "challenge", bend: 16 },
  { from: "challenge", to: "broaden", bend: -10 },
  { from: "challenge", to: "stress", bend: 10 },
  { from: "root", to: "organize", bend: 24 },
  { from: "organize", to: "zoom", bend: 8 },
  { from: "organize", to: "context", bend: 14 },
  { from: "organize", to: "emerge", bend: -8 },
  { from: "emerge", to: "flexible", bend: 9 },
  { from: "flexible", to: "evolve", bend: 4 },
  { from: "private", to: "yours", bend: -12 },
  { from: "private", to: "calm", bend: 12 },
  { from: "root", to: "ghost-left", bend: 18, ghost: true },
  { from: "flow", to: "ghost-top", bend: -12, ghost: true },
  { from: "challenge", to: "ghost-right", bend: 12, ghost: true },
];

export const voiceThoughts = [
  "The map should help ideas stay fluid without losing their relationships.",
  "I want the structure to appear after I finish the thought, not while I am still speaking.",
  "The AI can propose a connection, but I should decide whether it becomes part of the map.",
];

export const aiPrompts = [
  "Surface a hidden connection",
  "Challenge the current framing",
  "Suggest the next useful branch",
];
